In [323]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [324]:
data=pd.read_csv("/content/medical_insurance.csv")

In [325]:
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [326]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2772 entries, 0 to 2771
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       2772 non-null   int64
 1   sex       2772 non-null   object
 2   bmi       2772 non-null   float64
 3   children  2772 non-null   int64
 4   smoker    2772 non-null   object
 5   region    2772 non-null   object
 6   charges   2772 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 151.7+ KB

In [327]:
data.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [328]:
from sklearn.preprocessing import LabelEncoder

In [329]:
label_encoder=LabelEncoder()

In [330]:
data['sex'] = label_encoder.fit_transform(data['sex'])
data['smoker'] = label_encoder.fit_transform(data['smoker'])
data['region'] = label_encoder.fit_transform(data['region'])

In [331]:
data.describe()

,age,sex,bmi,children,smoker,region,charges
count,2772.000000,2772.000000,2772.000000,2772.000000,2772.000000,2772.000000,2772.000000
mean,39.109668,0.507215,30.701349,1.101732,0.203463,1.532468,13261.369959
std,14.081459,0.500038,6.129449,1.214806,0.402647,1.103467,12151.768945
min,18.000000,0.000000,15.960000,0.000000,0.000000,0.000000,1121.873900
25%,26.000000,0.000000,26.220000,0.000000,0.000000,1.000000,4687.797000
50%,39.000000,1.000000,30.447500,1.000000,0.000000,2.000000,9333.014350
75%,51.000000,1.000000,34.770000,2.000000,0.000000,2.000000,16577.779500
max,64.000000,1.000000,53.130000,5.000000,1.000000,3.000000,63770.428010

In [332]:
data.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [333]:
data.groupby('age')['charges'].describe().mean()

count       58.978723
mean     13755.698203
std      11283.008035
min       6391.109465
25%       7116.262378
50%       8036.556808
75%      16154.658811
max      45231.502894
dtype: float64

In [334]:
x = data[['age','sex','bmi','children','smoker','region']]
y = data[['charges']]

In [335]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x, y, train_size=0.75)

In [336]:
from sklearn.linear_model import LinearRegression
regression_model = LinearRegression()

In [337]:
regression_model.fit(x_train,y_train)

LinearRegression()

In [338]:
predictions = regression_model.predict(x_test)

In [339]:
from sklearn.metrics import r2_score
r_square_score = r2_score(y_test, predictions)
from sklearn.metrics import mean_squared_error
mse_score = mean_squared_error(y_test, predictions)
from sklearn.metrics import root_mean_squared_error
rmse_score = root_mean_squared_error(y_test, predictions)
from sklearn.metrics import mean_absolute_error
mae_score = mean_absolute_error(y_test, predictions)

In [ ]:
print('R2 = ' , r_square_score)
print('MSE = ', mse_score)
print('RMSE = ', rmse_score)
print('MASE = ', mae_score)

R2 =  0.7619564189503061
MSE =  35340648.121509284
RMSE =  5944.800090962629
MASE =  4115.932331659886

In [341]:
pred_sample = predictions[:5].flatten()
actual_sample = y.values.flatten()[:5] if hasattr(y, 'values') else y[:5]

print(f"{'Predicted Charges':<20} | {'Actual Charges'}")
print("-" * 40)
for pred, actual in zip(pred_sample, actual_sample):
    print(pred, ' | ', actual)

Predicted Charges    | Actual Charges
----------------------------------------
9046.298257480032  |  16884.924
6954.042405907372  |  1725.5523
31983.136334175528  |  4449.462
5145.146973063935  |  21984.47061
11526.767021139354  |  3866.8552